// Generated by Wrangler on Wed Feb 28 2024 23:51:24 GMT+0900 (Japan Standard Time)
// by running `wrangler types`

interface Env {
  APP_URL: string;
  WORKS_SERVER_URL: string;
  BFF_SERVER_URL: string;
}
