// Generated by Wrangler on Sun Mar 17 2024 15:22:36 GMT+0900 (Japan Standard Time)
// by running `wrangler types`

export {};
declare global {
  const BASIC_AUTH_USERNAME: string;
  const BASIC_AUTH_PASSWORD: string;
}
