name = "portfolio"
main = "./build/server/index.js"
compatibility_date = "2024-02-23"

# workers_dev = true

[vars]
BASIC_AUTH_PASSWORD = ""
BASIC_AUTH_USERNAME = ""

# [site]
# bucket = "./public"

# [build]
# command = "npm run build"
